### ISSUE TITLE
beta value of MatrixEQTL results

### ISSUE THREAD

**Issue by Zhangj215** [andreyshabalin/MatrixEQTL#10]
Hi
Using MatrixEQTL R package, I am performing both cis and trans eQTL analyses in order to find some SNPs associated with some genes of interest. I try to understand the Beat value in the results, What does "Effect size estimate" mean here? I am wondering whether it can represent a trend in changes in gene expression levels in different genotypes.

**Comment by andreyshabalin** [comment]
The effect size estimate is the beta estimate from the linear regression of the gene on the SNP.

I hope this page brings some clearity:
http://www.bios.unc.edu/research/genomic_software/Matrix_eQTL/CompareResults.html

**Comment by Zhangj215** [comment]
Thank you very much, this is exactly the kind of thing I'm after.
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Andrey Shabalin<mailto:notifications@github.com>
发送时间: 2020年4月14日 12:46
收件人: andreyshabalin/MatrixEQTL<mailto:MatrixEQTL@noreply.github.com>
抄送: jiZhang<mailto:zhangj_wmu.edu@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [andreyshabalin/MatrixEQTL] beta value of MatrixEQTL results (#10)


Closed #10<https://github.com/andreyshabalin/MatrixEQTL/issues/10>.

―
