### ISSUE TITLE
trans-QTL was defined as cis-QTL

### ISSUE THREAD

**Issue by wdyyy** [andreyshabalin/MatrixEQTL#12]
Dear Andrey Shabalin

I have met a strange problem while using MatrixEQTL. In my study, **some results that should have been defined as trans QTL were defined as cis QTLs**. In other words, **some cis-QTLs have a distance over 1e6 bp between SNP and its gene**. The distance is the minimum value of the absolute value of the distance between SNP and both ends of the gene.
```text
    distance = min( abs( snp_position - gene_start ), abs( snp_position - gene_end )  )
```

there are some of the _wrong_ QTLs:

qtl_type | SNP_ID | SNP_chr | SNP_loc | ref | alt | gene_ID | gene_chr | gene_start | gene_end | gene_strand | beta | t_stat | p | distance
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
cis | rs7088262 | chr10 | 49836108 | A | G | BMS1P5 | chr10 | 46737615 | 46762892 | -;chr10 | -0.23 | -3.5 | 4.88E-04 | 3.073216
cis | rs61838734 | chr10 | 49681118 | T | C | BMS1P5 | chr10 | 46737615 | 46762892 | -;chr10 | 0.14 | 3.74 | 1.91E-04 | 2.918226
cis | rs72783091 | chr10 | 49680879 | A | C | BMS1P5 | chr10 | 46737615 | 46762892 | -;chr10 | 0.13 | 3.63 | 2.92E-04 | 2.917987
cis | rs200554992 | chr10 | 49680859 | TA | T | BMS1P5 | chr10 | 46737615 | 46762892 | -;chr10 | 0.13 | 3.47 | 5.34E-04 | 2.917967
cis | rs56342922 | chr10 | 49680623 | A | G | BMS1P5 | chr10 | 46737615 | 46762892 | -;chr10 | 0.14 | 3.68 | 2.46E-04 | 2.917731
cis | rs7093726 | chr10 | 49678147 | T | G | BMS1P5 | chr10 | 46737615 | 46762892 | -;chr10 | 0.14 | 3.68 | 2.46E-04 | 2.915255
cis | rs7069220 | chr10 | 49678060 | C | T | BMS1P5 | chr10 | 46737615 | 46762892 | -;chr10 | 0.13 | 3.51 | 4.59E-04 | 2.915168
cis | rs3906889 | chr10 | 49677182 | G | C | BMS1P5 | chr10 | 46737615 | 46762892 | -;chr10 | 0.13 | 3.63 | 3.02E-04 | 2.91429

some of the QTLs even have SNP and gene in different chromosomes:

cis | rs2869546 | chr15 | 78907345 | C | T | SNORA63 | chr3 | 186505088 | 186505222 | + | -0.15 | -3.82 | 1.41E-04
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
cis | rs7182583 | chr15 | 78899210 | G | C | SNORA63 | chr3 | 186505088 | 186505222 | + | 0.14 | 3.57 | 3.77E-04
cis | rs9920189 | chr15 | 78666311 | G | T | SNORA63 | chr3 | 186505088 | 186505222 | + | 0.14 | 3.62 | 3.07E-04

Do you know why does it happen and how to solve it?

**Comment by andreyshabalin** [comment]
Hi EastsunW,

I'm happy to investigate.

Would you mind sharing your gene/SNP location files you were using?
And the genotype and gene expression files (actual values can be replaced with zeros).

My e-mail is: andrey.shabalin@gmail.com

Andrey
