### ISSUE TITLE
Help understanding option 'noFDRsaveMemory' in Matrix eQTL

### ISSUE THREAD

**Issue by sharvari14** [andreyshabalin/MatrixEQTL#14]
Dear Dr.Shabalin,

I am writing to seek your help in understanding the 'noFDRsaveMemory' option in Matrix eQTL function. Using this option as FALSE and TRUE, results in outputs with significantly different raw p-values. For example, setting this option as FALSE, returns p-values as low as e-300, while TRUE returns p-values ~e-15

I've read the paper and looked at the GitHub page, but couldn't get a better understanding of this behaviour. I would really appreciate it if you could shed some light on this, or point me to literature that can help to explain this behaviour. 

Thank you

**Comment by andreyshabalin** [comment]
Dear @sharvari14,

The results should be the same regardless of the `noFDRsaveMemory` parameter, but with it set to `TRUE` the output is not sorted by p-value. So the top of the file would look different.

Do you actually observe different p-values for the same gene-SNP pair?

If so, can you provide a reproducible example I can run?

Thank you,

Andrey

**Comment by gujjas** [comment]
Hi Andrey,

Thank you so much for the reply. You are right. The p-values are the same for the same gene-SNP pair. Sorry about that. 

I would like to confirm if it's expected to get very small p-values/FDR from this tool?
SNP     gene    beta    t-stat  p-value FDR
snp1     gene1   Inf     2.2250738585072e-308    **1.08110553592833e-302**
snp2     gene2    0.547772328108398       392.623084826711        2.2250738585072e-308    **1.08110553592833e-302**
snp2     gene2    0.547772328108398       392.623084826711        2.2250738585072e-308    **1.08110553592833e-302**
snp3     gene3   0.566147507210239       303.377306552224        2.2250738585072e-308    **1.08110553592833e-302**

Appreciate all the help.
Thank you.
