### ISSUE TITLE
Multiallelic variants

### ISSUE THREAD

**Issue by Tijs-dot** [andreyshabalin/MatrixEQTL#15]
Dear Dr. Shabalin,

I amtrying to perform an eQTL analysis using your tool, using genotypes obtained for HLA genes. These genes have many different possible alleles, which makes annotating them with either 0,1 or 2 problematic. 

Is there a way to input such multiallelic variants in MatrixEQTL?

Kind regards,
Tijs

**Comment by andreyshabalin** [comment]
What would be the linear model you'd like to estimate with such data?

**Comment by Tijs-dot** [comment]
Simple linear regression with additive effect. I have just under 90 samples for which I have obtained genotypes and gene expression data, and I have their covariate data as well.

**Comment by andreyshabalin** [comment]
Sorry, Matrix eQTL doesn't support such analysis.
