### ISSUE TITLE
Non-parametric linear regression

### ISSUE THREAD

**Issue by Yijun-Tian** [andreyshabalin/MatrixEQTL#16]
Hello Andreyshabalin,
The MatrixEQTL is very classical and robust in our eQTL analysis. My question here is more like a request instead of a issue. Since I am using single cell sequencing data for QTL analysis, is there a way to add useModel = "non-parametric linear model" to your options to fit it to single cell data distribution?
Thanks,
Yijun

**Comment by andreyshabalin** [comment]
What "non-parametric linear model" do you have in mind?

**Comment by Yijun-Tian** [comment]
> What "non-parametric linear model" do you have in mind?

Thank you Andrey for the prompt reply. I don’t have a specific model in mind to try yet, but this page gave a lot of candidate models for non-parametric regressions: https://rcompanion.org/handbook/F_12.html. In my analysis, the genotype info will still be the same 0,1,2 type, but the gene expression of single cell sequencing will include a lot of zero numbers. I used the “modelLINEAR” in my previous analysis, but the results seemed too good to be true. I think the Kendall–Theil Sen Siegel nonparametric linear regression (outlined in above link) might be a good non-parametric model in this case, but it may need some optimization. I can attach some example data that can be piped in the MatrixEQTL for a test run.

**Comment by andreyshabalin** [comment]
Well, no way I can do local regression within Matrix eQTL framework.

**Comment by Yijun-Tian** [comment]
> Well, no way I can do local regression within Matrix eQTL framework.

Thanks a lot, Andrey, and I agree with you that local regression is impossible since the restricted x variable. I'll close this post and stay tuned for any update for MatrixEQTL!

**Comment by Yijun-Tian** [comment]
Hello Andrey,
As we discussed last time, after lots of searching, do you think it will be possible to include this zeroinfl() model in the matrixeQTL to facilitate the QTL detection in single cell data? 

https://github.com/XuegongLab/SCeQTL/blob/master/R/calc.p.value.R

**Comment by andreyshabalin** [comment]
No

**Comment by Yijun-Tian** [comment]
Thanks for the quick reply, though.
