### ISSUE TITLE
Error in findInterval

### ISSUE THREAD

**Issue by ipiras** [andreyshabalin/MatrixEQTL#18]
Hello, I am encountering this error when running Matrix_eQTL_main:

Error in findInterval(x = stats.for.hist, vec = statbins1) : 
  'vec' must be sorted non-decreasingly and not contain NAs
Calls: Matrix_eQTL_main -> <Anonymous> -> tabulate -> findInterval

Another dataset I generated using the same script works without any issue when I run Matrix_eQTL_main. Basically, I splitted patients and controls samples from the main data files to run the eQTL separately. The patient group files run correctly, but not the controls.
I cannot understand the problem.
Can I please share by email my data and script? I was trying here but probably the files are too big to be shared.
Thanks
Ignazio

**Comment by andreyshabalin** [comment]
Hi Ignazio,

Yes, I'll be happy to help you.

Please share the data and the code you are running with me via andrey.shabalin@gmail.com

Andrey

**Comment by andreyshabalin** [comment]
Hi Ignazio,

I've pushed a fix to the issue revealed by your data.
https://github.com/andreyshabalin/MatrixEQTL/commit/7e5c1cb7a7a0c2afe4a7efd697e0de7b99b44729

Please try the updated version by running:

    if(!requireNamespace("devtools", quietly = TRUE))
        install.packages("devtools")
    devtools::install_github("andreyshabalin/MatrixEQTL")

I'm closing the issue. Please reopen it if the error didn't go away.

Andrey
