### ISSUE TITLE
Order of Matrix eQTL output

### ISSUE THREAD

**Issue by QinqinHuang** [andreyshabalin/MatrixEQTL#2]
Hi Andrey,
Thanks for this amazing tool! In the output of Matrix eQTL, the most significant association ranks the first. When I was using it to map eQTLs in my simulated datasets, I found that some associations had different t-statistics but the same p-value (I think they may reach the minimum that can be calculated/displayed by R: 2.225074e-308). For these associations (or SNPs, they were for the same eGene), they are ordered by genomic locations. I was wondering whether it would make more sense if these SNPs could be sorted by t-statstics, which indicate significance levels. 
Best,
Qinqin
![screen shot 2017-09-04 at 2 52 09 pm](https://user-images.githubusercontent.com/10149527/30012135-b4d4ceac-9180-11e7-9ab9-7e431636f9dc.png)

**Comment by andreyshabalin** [comment]
Hi Qinqin,
You are right, I hate zero p-values and I set them to `.Machine$double.xmin` in Matrix eQTL.
I agree with you on the order of the output. It's an easy fix.
I'll commit the update to Github tonight.
Thank you.
Andrey

**Comment by andreyshabalin** [comment]
I've committed the update.
I'm closing this issue now.

**Comment by QinqinHuang** [comment]
Thanks Andrey!
