### ISSUE TITLE
Significant trans eQTLs are no longer significant when cis window increases

### ISSUE THREAD

**Issue by katec04** [andreyshabalin/MatrixEQTL#20]
Hi there,

I'm currently running MatrixEQTL to do methQTLs and I noticed something peculiar in my results. 

Last week, I ran MatrixEQTL with separate cis and trans p-value thresholds. I used a cis p-value threshold of 1e-8 and a trans p-value threshold of 1e-14. I originally set a cis window of 10 kB. When I got my results back, there were 40,000 hits for trans, but zero hits for cis. I noticed that for a few trans hits, the associated SNP and methylation site were less than 50 kB apart. For one trans hit, they were 32 kB apart, for another, 22 kB, etc. 

I reran MatrixEQTL with the same p-values, but I changed the cis window to 50 kB. I still have 0 cis hits. I am confused because my trans hits that were within 50 kB should now be cis hits, given I increased the cis window and the trans p-value is more stringent than the cis p-value. 

I was wondering if you could help me understand why this might be occurring. Furthermore, if I ran MatrixEQTL without specifying a cis window, do you think this problem would be solved? Thank you in advance for your help!

**Comment by andreyshabalin** [comment]
Hi @katec04,

Would you check `me$cis$ntests` please.
I wonder if your annotation files for genotypes and for methylation mismatch.
For example, they could have different names for the same chromosomes (chr1 vs 1).

Andrey

**Comment by katec04** [comment]
You're right - changing the chromosome naming solved the issue. Thanks!
