### ISSUE TITLE
how to add kinship matrix

### ISSUE THREAD

**Issue by zhoudreames** [andreyshabalin/MatrixEQTL#21]
In the matirxEQTL tutorial, this process does not add a kinship matrix to run the eQTL analysis. However, My data is family-level, and I want to add the kinship to run the eQTL analysis, How to do it? Thanks~

**Comment by zhoudreames** [comment]
@andreyshabalin I am so sorry to disturb you, can you help me, Thanks~

**Comment by andreyshabalin** [comment]
Hi @zhoudreames,

Matrix eQTL does not fully support linear mixed models.
I suggest you run it without using a kinship matrix with a liberal p-value threshold and then run linear mixed model on top gene-SNP pairs to get precise p-values.

Andrey

**Comment by zhoudreames** [comment]
Thanks~
