### ISSUE TITLE
calculation only cis-eQTL

### ISSUE THREAD

**Issue by Asppagh** [andreyshabalin/MatrixEQTL#22]
Is there any option to calculate cis-eQTL ?
currently is does both cis and trans at the same time, but in many case we need to do only one of them.
Thanks!

**Comment by andreyshabalin** [comment]
Yes, set distant eQTL p-value threshold to 0.

**Comment by andreyshabalin** [comment]
Per http://www.bios.unc.edu/research/genomic_software/Matrix_eQTL/html/Matrix_eQTL_main.html

Set pvOutputThreshold = 0 and pvOutputThreshold.cis > 0 to perform eQTL analysis for local gene-SNP pairs only. Local associations significant at pvOutputThreshold.cis level will be recorded in output_file_name.cis and in the returned object.
