### ISSUE TITLE
Is this P-value comparable to that of GWAS analysis?

### ISSUE THREAD

**Issue by lizhao007** [andreyshabalin/MatrixEQTL#25]
Thanks for your useful software. The p values I get by using Matrix_eQTL are very small, and some of them can reach p=2.2250738585072e-308, but the p values of GWAS or eGWAS are generally not more than 1e-10. Are the two methods the same? Can the p values obtained by the two methods be calculated together? How should the significance threshold of Matrix_eQTL be determined?

Looking forward to your reply

**Comment by andreyshabalin** [comment]
Yes. Please consult this page:

http://www.bios.unc.edu/research/genomic_software/Matrix_eQTL/CompareResults.html

**Comment by andreyshabalin** [comment]
Would you be able to provide me a reproducible example of a mismatch in the gwas results?
