### ISSUE TITLE
p-values very small 

### ISSUE THREAD

**Issue by winnerHeyc** [andreyshabalin/MatrixEQTL#28]
Why do extremely small p-values appear in the Matrix results? Are these due to calculation issues, and can they be used directly?
head cis_eqtlout
SNP     gene    beta    t-stat  p-value FDR
Chr1_1025645    MSTRG.341.1     13.07   Inf     2.2250738585072e-308    2.91956304784701e-304
Chr1_1025645    MSTRG.343.1     4.09    Inf     2.2250738585072e-308    2.91956304784701e-304
Chr1_1307252    MSTRG.341.1     4.35666666666667        Inf     2.2250738585072e-308    2.91956304784701e-304
Chr1_1307252    MSTRG.343.1     1.36333333333333        Inf     2.2250738585072e-308    2.91956304784701e-304
Chr1_1505533    MSTRG.341.1     13.07   Inf     2.2250738585072e-308    2.91956304784701e-304
Chr1_1516057    MSTRG.341.1     13.07   Inf     2.2250738585072e-308    2.91956304784701e-304
Chr1_1505533    MSTRG.343.1     4.09    Inf     2.2250738585072e-308    2.91956304784701e-304
Chr1_1516057    MSTRG.343.1     4.09    Inf     2.2250738585072e-308    2.91956304784701e-304
Chr1_1573233    MSTRG.341.1     13.07   Inf     2.2250738585072e-308    2.91956304784701e-304

**Comment by andreyshabalin** [comment]
If you have infinite t-statistic, you have perfect correlation between the variables. The p-value is then essentially zero which you see here.
