### ISSUE TITLE
significant p value

### ISSUE THREAD

**Issue by SumaDabi** [andreyshabalin/MatrixEQTL#31]
Hi,
I am currently using matrix-eQTL for eQTL analysis of my wheat dataset. Is there a way to determine the best threshold for identifying cis and trans eQTLs? For example, how can I choose the value for pvOutputThreshold_cis and pvOutputThreshold_trans? I used 10-5 in both cases, but it provided many cis and trans eqtl, which may not be true. Also, I used the min.pv.by.genesnp = =T option, it provided me the p value number for each gene and snp, but I am confused about which one I should choose for the threshold. maybe I am missing something. Please guide me in this regard.
Thank you.

**Comment by andreyshabalin** [comment]
Hi Suma Bala Dabi,

The p-value threshold can be based on the number of local and distant tests.
Those numbers are reported by MatrixEQTL in the returned `me` object.

Andrey

**Comment by SumaDabi** [comment]
Hi Andrey,
Thank you so much for your reply.  I checked the number of tests for cis and trans,
 matrix_eqtl$cis$ntests
563866
 matrix_eqtl$trans$ntests
2871359314
I am sorry for the naive question, but how do I decide the p-value from this value? Should I divide it by the number of samples or something else?

**Comment by andreyshabalin** [comment]
A good p-value threshold to start with would be `pvOutputThreshold_cis = 1/matrix_eqtl$cis$ntests` and `pvOutputThreshold_trans = 1/matrix_eqtl$trans$ntests`. It's also very helpful to inspect the QQ-plots for local and distant tests.

**Comment by SumaDabi** [comment]
Thank you so much for your help. I am closing this issue.

**Comment by koujiaodahan** [comment]
why  

> A good p-value threshold to start with would be `pvOutputThreshold_cis = 1/matrix_eqtl$cis$ntests` and `pvOutputThreshold_trans = 1/matrix_eqtl$trans$ntests`. It's also very helpful to inspect the QQ-plots for local and distant tests.

Hi, I’m wondering: why is the threshold set to 1/ntests instead of the more conventional Bonferroni-corrected threshold of 0.05 / ntests?

**Comment by andreyshabalin** [comment]
They are of the same order of magnitude and mine allows for more liberal FDR correction.

**Comment by koujiaodahan** [comment]
> They are of the same order of magnitude and mine allows for more liberal FDR correction.

Just to confirm: the 1/nTests threshold is only for preliminary filtering, and the final significance should still be determined by FDR < 0.05. Is that correct?”

**Comment by andreyshabalin** [comment]
Yes, I explicitly suggested the 1/nTests threshold as the parameter for Matrix eQTL.
Then, the recorded p-values can be thresholded using the FDR approach.

**Comment by koujiaodahan** [comment]
> Yes, I explicitly suggested the 1/nTests threshold as the parameter for Matrix eQTL. Then, the recorded p-values can be thresholded using the FDR approach.

I would like to clarify if the calculated FDR values are sensitive to the pvOutputThreshold parameter.
Specifically, if I change the threshold from 1e-5 to 1/nTests, will the FDR (q-values) for the retained top hits remain the same? Does Matrix eQTL calculate FDR based on the total number of tests regardless of the output threshold, or does the threshold affect the estimation?

**Comment by Jia-nianhua** [comment]
> > Yes, I explicitly suggested the 1/nTests threshold as the parameter for Matrix eQTL. Then, the recorded p-values can be thresholded using the FDR approach.
> 
> I would like to clarify if the calculated FDR values are sensitive to the pvOutputThreshold parameter. Specifically, if I change the threshold from 1e-5 to 1/nTests, will the FDR (q-values) for the retained top hits remain the same? Does Matrix eQTL calculate FDR based on the total number of tests regardless of the output threshold, or does the threshold affect the estimation?

I also want to know.
