### ISSUE TITLE
The program was killed before it was finished, but no error was reported

### ISSUE THREAD

**Issue by huang-baisha** [andreyshabalin/MatrixEQTL#32]
Hi,
when I use MatrixEQTL，it was killed before it was finished, but no error was reported.
I don't know why. 
The follw is my command:
`nohup Rscript MatrixEQTL.r genotype_transpose.txt snpsloc.txt all_ASEs.v2.psi ASEsLoc.txt ASEs 0.001 > MatrixEQTL.nohup 2>&1 &`

10.51% done, 6,921,355,928 trans-eQTLs
10.51% done, 6,921,909,027 trans-eQTLs
10.51% done, 152,195 cis-eQTLs, 6,922,559,802 trans-eQTLs
10.51% done, 153,006 cis-eQTLs, 6,923,188,512 trans-eQTLs
10.52% done, 6,923,769,043 trans-eQTLs
10.52% done, 6,924,378,878 trans-eQTLs
10.52% done, 6,924,934,506 trans-eQTLs
10.52% done, 6,925,532,313 trans-eQTLs
10.52% done, 6,926,320,359 trans-eQTLs

when it run to "10.52% done, 6,926,320,359 trans-eQTLs",it was killed.
Can you provide me with some helpful suggestion. 
Thanks!

**Comment by andreyshabalin** [comment]
Drastically lower the value threshold for distant (trans) tests. To 1e-10 at least.

**Comment by huang-baisha** [comment]
Thank you! I will try it.But is this threshold too strict? It will filter out a lot of other information. I want to know what is causing this (memory?)

**Comment by andreyshabalin** [comment]
At the threshold you are using you should expect about 60 billion significant distant eQTLs.
Are you really interested in this many?

**Comment by huang-baisha** [comment]
Thank you for your answer！
