### ISSUE TITLE
Colinear or zero covariates detected error

### ISSUE THREAD

**Issue by HanyingYan** [andreyshabalin/MatrixEQTL#33]
Hi I got this "Colinear or zero covariates detected" and I guess this is because I created separate columns for all categories in a categorical variable, which introduce collinearity. So I wonder if removing one of the dummy columns as a reference level is the correct way to avoid this.

Thanks,
Hanying

**Comment by andreyshabalin** [comment]
Yes, removing one of the dummy columns is the solution.
