### ISSUE TITLE
Data set too large?

### ISSUE THREAD

**Issue by katiearacena** [andreyshabalin/MatrixEQTL#9]
Hello,

I am trying to use MatrixEQTL to detect DNA methylation QTL. I am currently using a window size of 1 kb to detect cis-QTL. 

I am suspicious that I may have more data than MatrixEQTL is designed to handle. I am currently using only chr1, but have 1.1 million CpG sites I am trying to test. During QTL mapping I can only progress to 7.71% done, not 100%. This is my last line:

` 7.71% done, 4,185,210 cis-eQTLs`
 `7.71% done, 4,185,817 cis-eQTLs`
`Task finished in 489.067 seconds`

Do you have any insight if this could be due to the large number of CpG sites or could it be another issue? Thanks!

**Comment by andreyshabalin** [comment]
Dear Katie,

Matrix eQTL can handle a lot of data and I do not think you reached the limit (or even close to it).

I strongly believe Matrix eQTL ran correctly on your data.
The confusion comes from the way it reports the progress.
Namely, it was going through the SNPs,
and reporting progress as it goes. Once it was done with SNPs on chr1,
which is about 8% of the genome, it started looking at SNPs on other chromosomes,
which did not have any nearby methylation markers in your data.
Thus, it was just skipping it, quickly reaching the end and saying "Task finished".

Andrey

**Comment by katiearacena** [comment]
Hi Andrey,

That makes a lot of sense. Thanks for the quick response and help!

Katie
